use_frameworks!
platform :ios, '8.0'
#inhibit_all_warnings!

target 'MathpixClient_Example' do
    pod 'MathpixClient', :path => '../'
    
    target 'MathpixClient_Tests' do
        inherit! :search_paths
        inhibit_all_warnings!
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 7.0.0'
    end
end
