use_frameworks!
platform :ios, '12.0'
#inhibit_all_warnings!

target 'MathpixClient_Example' do
    pod 'MathpixClient', :path => '../'
    
    target 'MathpixClient_Tests' do
        inherit! :search_paths
        inhibit_all_warnings!
        pod 'Quick', '~> 5.0.0'
        pod 'Nimble', '~> 10.0.0'
    end
end
